### ISSUE TITLE
Getting 100% performance on all conversational datasets

### ISSUE THREAD

**Issue by ypuzikov** [Guzpenha/transformer_rankers#5] opened 2021-08-16 16:19 UTC
Hi, Gustavo! Thank you for sharing the code for the paper!

A strange complaint, but I am getting close to perfect performance on the conversational datasets :) How is this possible? 
I have taken the `transformer_rankers/examples/pointwise_bert_ranker.py` code as a base script, set the hyperparameters as mentioned in the paper. After the model has been trained, I get 1.0 for all three metrics (R_10@1, R_10@5, map) on mantis, and 0.99-1.0 scores on msdialog and udc data. 

I also tried using a random negative sampler (instead of the BM25 one) on msdialog and got the following results: R_10@1=0.8061, R_10@5=0.969, map=0.8765. But this is still much higher than expected. Can you maybe share the end-to-end training script for one of those datasets? Say, UDC, since it is the smallest one.

**Comment by Guzpenha** [comment] 2021-08-16 16:35
Hi @ypuzikov thanks for the message,

I am not sure why you are getting such high numbers when using BM25, it should not look like that. What is the number of negative samples you used? On most of my experiments I have used num_ns_eval=9 so that we have 10 candidates (one relevant + nine random/bm25 sampled).

Someone contacted me through email saying that they observed a high number due to a problem where ' " '  characters were added only to the negative samples when using BM25 if I recall correctly, and he fixed by removing them (BERT would easily recognize a response that is not relevant by using this artifact added by mistake).

You can see a full script to reproduce baseline results on the 3 datasets here: 

[https://wandb.ai/guz/library-crr-bert-baseline/reports/BERT-ranker-baselines-for-CRR--Vmlldzo0NDcyMzU](https://wandb.ai/guz/library-crr-bert-baseline/reports/BERT-ranker-baselines-for-CRR--Vmlldzo0NDcyMzU)

It also contains the results for you to compare. Can you try to run it like this (hyperparameters) and see if the problem persists?

I am currently not working, but if you cannot reproduce the results of this report I will try check it myself if I can get the same results of this wandb report above. I believe this problem might have something to do with a change in the anserini code (which does the bm25 negative sampling) and how I use the library that is adding the extra ' " '.

**Comment by ypuzikov** [comment] 2021-08-16 16:50
Thanks for getting back so promptly ^^ I also used 9 negative samples for evaluation.
Thanks for the sample script, I will try running it and come back once the model is evaluated!

**Comment by ypuzikov** [comment] 2021-08-16 20:39
> Thanks for getting back so promptly ^^ I also used 9 negative samples for evaluation.
> Thanks for the sample script, I will try running it and come back once the model is evaluated!

Did that, still high scores: R_10@1=0.9964  R_10@5=1.0  map=1.0
I will do this eval on clean repo clone tomorrow morning and report eval results here.

**Comment by Guzpenha** [comment] 2021-08-17 11:00
I have done some quick testing and I believe this commit solves the bug. Let me know if you find the same @ypuzikov .

**Comment by ypuzikov** [comment] 2021-08-17 19:47
I pulled the changes and trained a model using the command you kindly provided. With these params:
```bash
--num_ns_eval 9 --num_ns_train 9 --num_epochs 1 --num_training_instances 300000
```
on msdialog I get the following numbers:
```bash
Test R_10@1 : 0.765347
Test R_10@5 : 0.974469
Test map : 0.855614
```
Table 1 from the paper says R_10@1 should be around 0.652, if I am reading it correctly.

**Comment by Guzpenha** [comment] 2021-08-17 19:57
Hi @ypuzikov, which paper are you refering to?

**Comment by Guzpenha** [comment] 2021-08-17 20:12
I think you mean MSDialog  bm25 to bm25 on Table 1 of "On the Calibration and Uncertainty of Neural Learning to Rank Models". For that experiment I used this branch of the repository: 

[https://github.com/Guzpenha/transformer_rankers/tree/uncertainty_estimation](https://github.com/Guzpenha/transformer_rankers/tree/uncertainty_estimation)

I believe we used num_ns_train = 1, since following this [script](https://github.com/Guzpenha/transformer_rankers/blob/uncertainty_estimation/transformer_rankers/scripts/reproduce_uncertainty_paper.sh) leads to the following scripts : 

https://github.com/Guzpenha/transformer_rankers/blob/uncertainty_estimation/transformer_rankers/scripts/run_crr_MC_dropout.sh

https://github.com/Guzpenha/transformer_rankers/blob/uncertainty_estimation/transformer_rankers/scripts/run_crr_ensemble.sh

And both have the following :
```
            --num_epochs 1 \
            --train_batch_size 6 \
            --val_batch_size 6 \
            --num_ns_train 1 \
            --num_ns_eval 9 \
```
So it is makes sense that using ns_train = 1 for training leads to the 0.652 while with ns_train= 9 and a bigger batch we get closer to 0.76 (which is also what we get on dev here for mantis : https://wandb.ai/guz/library-crr-bert-baseline/reports/BERT-ranker-baselines-for-CRR--Vmlldzo0NDcyMzU)

I will close this issue since the main bug of high effectiveness introduced by a change in anserini was solved, but feel free to send me an email if you have any questions about reproducing this paper !

**Comment by ypuzikov** [comment] 2021-08-17 20:24
Sure, thanks!

**Closed as completed** 2021-08-20 12:42 UTC
